### ISSUE TITLE
[LOC]Back-Translation "マイクロソフト フロー Azure クストー"→"Microsoft Flow Azure Kusto"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/dataexplorer-docs.ja-jp#1]
![kusto_flow](https://user-images.githubusercontent.com/40815708/81393647-ae448900-915b-11ea-9bca-3bfa46415274.png)

https://docs.microsoft.com/ja-jp/azure/data-explorer/kusto/tools/flow

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 626ab6de-39c6-827b-78e2-1a518731356a
* Version Independent ID: b1627aae-64f8-6cd9-791a-0201130f9c5d
* Content: [マイクロソフト フロー Azure クストー コネクタ (プレビュー) - Azure データ エクスプローラー](https://docs.microsoft.com/ja-jp/azure/data-explorer/kusto/tools/flow)
* Content Source: [data-explorer/kusto/tools/flow.md](https://github.com/MicrosoftDocs/dataexplorer-docs.ja-jp/blob/master/data-explorer/kusto/tools/flow.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by srvbpigh** [comment]
Hello, @hyoshioka0128
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
@hyoshioka0128 様:  

投稿いただき、ありがとうございます。 

現在、機械翻訳されたコンテンツに対する翻訳の問題へのコントリビューションはできません。 

人間が翻訳したコンテンツに関するフィードバックやご意見をお寄せください。人間が翻訳したコンテンツは機械翻訳エンジンをトレーニングするために使用されているため、お客様は、時間が経つにつれ人間および機械の両方による翻訳の質を向上させることに貢献できます。 

人間が翻訳したトピックは、各コンテンツ ファイルのヘッダーの translationtype メタデータ値 "HT" (機械翻訳の場合は "MT") によって、機械翻訳されたトピックと区別できます。 


サポートいただきありがとうございます。
